-- kangaroo bus to handle the publishing of data generated by kangaroo


local M = {}

local state = {
    seq = 0,
    timestamp_ms = 0,
    lat = nil,
    lng = nil,
    vn = 0,
    ve = 0,
    heading_deg = 0,
    speed_mps = 0,
}

function M.publish(loc, vn, ve, heading_deg, speed_mps, now_ms)
    if loc == nil then
        return false
    end
    state.seq = state.seq + 1
    state.timestamp_ms = now_ms
    state.lat = loc:lat()
    state.lng = loc:lng()
    state.vn = vn or 0
    state.ve = ve or 0
    state.heading_deg = heading_deg or 0
    state.speed_mps = speed_mps or 0
    return true
end

function M.get()
    if state.lat == nil then
        return nil
    end

    local loc = Location()
    loc:lat(state.lat)
    loc:lng(state.lng)

    return {
        seq = state.seq,
        timestamp_ms = state.timestamp_ms,
        loc = loc,
        vn = state.vn,
        ve = state.ve,
        heading_deg = state.heading_deg,
        speed_mps = state.speed_mps
    }
end

return M